<a href="https://colab.research.google.com/github/shaan-byte/python_ds_colab/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import time

print(np.__version__)

2.0.2


Create numpy arrays uisng a list

In [7]:
messi_goals=[2,3,4,2,5,7,9,6]
np_messi=np.array(messi_goals,dtype="int")
print(np_messi)
print(type(np_messi))
total=np.sum(np_messi)
avg=np.mean=(np_messi)
above_5=np_messi[np_messi>5]
print(total)
print(avg)
print(above_5)


[2 3 4 2 5 7 9 6]
<class 'numpy.ndarray'>
38
[2 3 4 2 5 7 9 6]
[7 9 6]


In [14]:
zero=np.zeros(14) #fills 14 elements with 0
print(zero)
ones=np.ones(12) #fills 12 elements with 1
print(ones)
arange=np.arange(1,15,2) #like range in for loops (start,stop,step)
print(arange)
graph=np.linspace(6,12,30) #creates evenly spaced values between start and stop using the number specified(str,stop,step)
print(graph) #useful for graph plotting
fill=np.full(10,fill_value=7) #fills 10 elemnts with the value specified
print(fill)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 1  3  5  7  9 11 13]
[ 6.          6.20689655  6.4137931   6.62068966  6.82758621  7.03448276
  7.24137931  7.44827586  7.65517241  7.86206897  8.06896552  8.27586207
  8.48275862  8.68965517  8.89655172  9.10344828  9.31034483  9.51724138
  9.72413793  9.93103448 10.13793103 10.34482759 10.55172414 10.75862069
 10.96551724 11.17241379 11.37931034 11.5862069  11.79310345 12.        ]
[7 7 7 7 7 7 7 7 7 7]


Array properties

In [21]:
messi_shape=np_messi.shape # dimension of a tuple messi array has 8 values
print(messi_shape)
messi_size=np_messi.size #total no of elements in messi array
print(messi_size)
messi_dtype=np_messi.dtype #data type of messi array
print(messi_dtype)
messi_ndim=np_messi.ndim #no of dimensions
print(messi_ndim)
messi_nbytes=np_messi.nbytes #total no of bytes
print(messi_nbytes)

two_d=np.array([[1,2,3],[4,5,6]]) #2D array
print(f"Size of two d array: {two_d}")

twod_size=two_d.size
print(twod_size)

twod_shape=two_d.shape
print(twod_shape)

twod_ndim=two_d.ndim
print(twod_ndim)

twod_dtype=two_d.dtype
print(twod_dtype)

twod_nbytes=two_d.nbytes
print(twod_nbytes)

(8,)
8
int64
1
64
Size of two d array: [[1 2 3]
 [4 5 6]]
6
(2, 3)
2
int64
48


Multidimesional Array

In [28]:
threed_array=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
print("="*45)
print(threed_array)
print("="*45)
print(threed_array.shape)
print("="*45)
print(threed_array.size)
print("="*45)
print(threed_array.ndim)
print("="*45)
print(threed_array.dtype)
print("="*45)
print(threed_array.nbytes)
print("="*45)
print(f"Accessing elements:{threed_array[0,1,2]}")

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
(2, 3, 3)
18
3
int64
144
Accessing elements:6


Opearations

In [35]:
messi_twice=np_messi*2
print(f"twice of every messi array element {messi_twice}") #can be done with other opeations too
print(f"Sum of Twice goals:{messi_twice.sum()}")
print(f"Mean of Twice goals:{messi_twice.mean()}")
print(f"Max of Twice goals:{messi_twice.max()}")
print(f"Min of Twice goals:{messi_twice.min()}")
print(f"Argmax of Twice goals:{messi_twice.argmax()}") #returns index of max value
print(f"Argmin of Twice goals:{messi_twice.argmin()}") #returns index of min value
print(f"Standard Deviation of Twice goals:{messi_twice.std()}") #standard deviation
print(f"Variance of Twice goals:{messi_twice.var()}") #Variance


twice of every messi array element [ 4  6  8  4 10 14 18 12]
Sum of Twice goals:76
Mean of Twice goals:9.5
Max of Twice goals:18
Min of Twice goals:4
Argmax of Twice goals:6
Argmin of Twice goals:0
Standard Deviation of Twice goals:4.663689526544408
Variance of Twice goals:21.75
